### ISSUE TITLE
Are you accepting PR's, and can there be a table of contents at top?

### ISSUE THREAD

**Issue by Ugleh** [fabiencelier/geoguessr-tips#1]
What they title said. Are you accepting PR's, and can there be a table of contents at top?

**Comment by fabiencelier** [comment]
Hello and welcome,

Yes I am accepting PRs ! A table of content is a great idea !

FYI In the future if the content get too big I was thinking about switching from markdown to a more structured site with a left menu

**Comment by fabiencelier** [comment]
I am closing this issue as I have added a table of content.

Feel free to make a PR if you want to contribute.
