### ISSUE TITLE
License Plate Requirement Map Key is wrong

### ISSUE THREAD

**Issue by TheJoeFin** [fabiencelier/geoguessr-tips#4]
Looking at the Wikipedia page compared to the map, they do not match. 

From Wikipedia:

Color | Requirement
----- | ------
Green | Only rear plates Required
Maroon | Front and rear plates required
Dark Maroon | Front and rear generally required with Exceptions

**Comment by fabiencelier** [comment]
Thank you for reporting, I will fix that

**Comment by fabiencelier** [comment]
Oh I see where my error comes from: the wiki page changed the order in the array with the list of states. I should fix that too

**Comment by fabiencelier** [comment]
It should be OK now
